version: 2
updates:
  - &composer-common
    package-ecosystem: "composer"
    directory: "/php72"
    schedule:
      interval: "daily"

  - <<: *composer-common
    directory: "/php73"

  - <<: *composer-common
    directory: "/php74"

  - <<: *composer-common
    directory: "/php80"

  - <<: *composer-common
    directory: "/php81"

  - <<: *composer-common
    directory: "/php82"

  - <<: *composer-common
    directory: "/php83"

  - <<: *composer-common
    directory: "/php84"

  - <<: *composer-common
    directory: "/php85"
