version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
executors:
  php56:
    docker:
      - image: cimg/php:5.6-browsers
  php70:
    docker:
      - image: cimg/php:7.0-browsers
  php71:
    docker:
      - image: cimg/php:7.1-browsers
  php72:
    docker:
      - image: cimg/php:7.2-browsers
  php73:
    docker:
      - image: cimg/php:7.3-browsers
  php74:
    docker:
      - image: cimg/php:7.4-browsers
  php80:
    docker:
      - image: cimg/php:8.0-browsers
  php81:
    docker:
      - image: cimg/php:8.1-browsers
commands:
  restore_caches:
    steps:
      - restore_cache:
          keys:
            - composer-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "_composer_cache_key" }}-{{ checksum "composer.lock" }}-{{ checksum "composer-php8.lock" }}
            # NOTE: Fallback to using the latest cache if no exact match is found
            - composer-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "_composer_cache_key" }}-{{ checksum "composer.lock" }}
            - composer-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "_composer_cache_key" }}-
            - composer-{{ .Environment.CIRCLE_STAGE }}-
            - composer-
  create_cache_key_files:
    steps:
      - run: echo $CIRCLECI_COMPORSER_CACHE_KEY
      - run:
          name: Write the composer cache key to a file
          command: |
            echo $CIRCLECI_COMPORSER_CACHE_KEY > _composer_cache_key
            cat _composer_cache_key
  save_caches:
    steps:
      - save_cache:
          paths:
            - vendor
          key: composer-{{ .Environment.CIRCLE_STAGE }}-{{ checksum "_composer_cache_key" }}-{{ checksum "composer.lock" }}-{{ checksum "composer-php8.lock" }}
jobs:
  test:
    environment:
      CIRCLECI_COMPORSER_CACHE_KEY: '2020122301'
    parameters:
      e:
        type: executor
      cache:
        type: boolean
        default: true
      composer_json:
        type: string
        default: composer.json
      phpunit_xml:
        type: string
        default: phpunit.xml
    executor: << parameters.e >>
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      # FIXME:
      - run: pwd
      - run:
          name: Check parameters
          command: |
            echo "parameters.cache: << parameters.cache >>"
            echo "parameters.composer_json: << parameters.composer_json >>"
            echo "parameters.phpunit_xml: << parameters.phpunit_xml >>"
      - when:
          condition: << parameters.cache >>
          steps:
            - create_cache_key_files
            - restore_caches
      - run: php -v
      - run: composer -V
      - run: google-chrome --version
      - run: chromedriver --version
      - run: java -jar /usr/local/bin/selenium.jar --version
      - run: COMPOSER=<< parameters.composer_json >> composer install --prefer-dist
      - when:
          condition: << parameters.cache >>
          steps:
            - save_caches
      - run:
          name: Run servers and test
          command: |
            java -jar /usr/local/bin/selenium.jar > /tmp/selenium.log 2> /tmp/selenium.error &
            tests/wait-for-it.sh localhost:4444 -t 0
            php -S 0.0.0.0:8000 > /tmp/server.log 2>&1 &
            tests/wait-for-it.sh localhost:8000 -t 0
            #vendor/bin/phpunit -c tests/<< parameters.phpunit_xml >>
            vendor/bin/phpunit -c tests/<< parameters.phpunit_xml >> --stderr -v --debug
workflows:
  workflow:
    jobs:
      - test:
          name: php56
          e: php56
          # NOTE: When there enable the cache, it doesn't work for some reason, so there disable it.
          cache: false
      - test:
          name: php70
          e: php70
      - test:
          name: php71
          e: php71
      - test:
          name: php72
          e: php72
      - test:
          name: php73
          e: php73
      - test:
          name: php74
          e: php74
      - test:
          name: php80
          e: php80
          composer_json: composer-php8.json
          phpunit_xml: phpunit-php8.xml
      - test:
          name: php81
          e: php81
          composer_json: composer-php8.json
          phpunit_xml: phpunit-php8.xml
